resource_types:
- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource


resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/slirunner
      ignore_paths: [ ./VERSION ]

  - name: container-image
    type: registry-image
    source:
      repository: cirocosta/slirunner
      username: ((docker-user))
      password: ((docker-password))

  - name: version
    type: semver
    source:
      driver: git
      uri: https://((github-token))@github.com/cirocosta/slirunner
      branch: master
      file: ./VERSION
      git_user: Ciro S. Costa <cscosta@pivotal.io>


jobs:
  - name: build
    public: true
    plan:
      - in_parallel:
        - {get: repository, trigger: true}
        - {get: version, trigger: true}
      - in_parallel:
          fail_fast: true
          steps:
            - task: build-image
              privileged: true
              params: {TARGET: "release"}
              file: repository/ci/tasks/build.yml
            - task: test
              privileged: true
              params: {TARGET: "test"}
              file: repository/ci/tasks/build.yml
      - put: container-image
        inputs: [image, version]
        get_params: {format: oci}
        params:
          image: image/image.tar
          additional_tags: version/version
